require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - vendor/bundle/**/*
    - Gemfile
    - db/schema.rb
    - bin/*
    - db/migrate/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Enabled: false